# -*- coding: utf-8 -*-
"""analizador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DqYaWGNYRD5-MzfJKfuDz02wt_iQbWO
"""

import streamlit as st
import pandas as pd

st.title("📊 Analizador de Datos CSV")
st.write("Sube tu archivo para visualizar los datos en una gráfica automática.")

# 1. Componente para subir el archivo desde la web
archivo_subido = st.file_uploader("Elige un archivo CSV", type=["csv"])

if archivo_subido is not None:
    # 2. Leer el archivo CSV usando Pandas
    df = pd.read_csv(archivo_subido)

    # 3. Mostrar una vista previa de la tabla en la página
    st.subheader("📋 Vista previa de los datos")
    st.dataframe(df.head())

    # 4. Intentar graficar las columnas numéricas de forma automática
    st.subheader("📈 Gráfica de líneas")
    columnas_numericas = df.select_dtypes(include=["number"]).columns

    if len(columnas_numericas) > 0:
        columna_elegida = st.selectbox("Selecciona la columna que quieres graficar:", columnas_numericas)
        st.line_chart(df[columna_elegida])
    else:
        st.warning("El archivo CSV no contiene columnas con datos numéricos para graficar.")