# -*- coding: utf-8 -*-
"""chatsimple

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvwJOudgsBnnWXZ649IPEbR0b8Wm1LIz
"""

import streamlit as st
from groq import Groq

st.title("🤖 Chatbot Simple")

# Esto buscará de forma segura la clave en la configuración de Streamlit
cliente = Groq(api_key=st.secrets["GROQ_API_KEY"])

pregunta = st.text_input("Hazme una pregunta:")

if pregunta:
    respuesta = cliente.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": pregunta}]
    )
    st.write(respuesta.choices.message.content)