# -*- coding: utf-8 -*-
"""chatbot-dataengineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/kevinespa/72a4b4313eaa303e927e840c33bf0766/chatbot-dataengineering.ipynb
"""

!pip install mysql-connector-python -q

import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
      host="146.190.146.6",
      port=3306,
      user="estudiante_sql",
      password="Academia100%",
      database="estudiantes_sql"
)

print("Conectado al servidor")

tablas = pd.read_sql("SHOW TABLES", conn)
print(tablas)

df = pd.read_sql("SELECT * FROM estudiantes LIMIT 5", conn)
print(df)

schema = pd.read_sql("DESCRIBE estudiantes", conn)
print(schema)

conn.close()

# Paso 1: Conseguir API key gratis
# → ve a console.groq.com
# → Sign up con tu correo (sin tarjeta)
# → API Keys → Create API Key → copiar

# Paso 2: Instalar en Colab
!pip install groq -q

# Paso 3: Primera llamada
from groq import Groq

cliente = Groq(api_key="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")

respuesta = cliente.chat.completions.create(
    model="llama-3.1-8b-instant",  # gratis y rápido
    messages=[
        {
            "role": "system",
            "content": "Eres un analista de datos experto. Responde siempre en español claro y conciso."
        },
        {
            "role": "user",
            "content": "¿Cuáles son las 3 preguntas más importantes que debería hacerle a mis datos de ventas?"
        }
    ],
    temperature=0.3,
    max_tokens=500
)

# La respuesta está aquí
texto = respuesta.choices[0].message.content
print(texto)

# Cuántos tokens usaste
print(f"Tokens usados: {respuesta.usage.total_tokens}")

#instalar
!pip install groq -q


from groq import Groq

cliente = Groq(api_key="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")

# Historial del chat
mensajes = [
    {
        "role": "system",
        "content": "Eres un analista de datos experto. Responde siempre en español claro y conciso."
    }
]

print("Chat iniciado.")
print("Escribe 'salir' para terminar.\n")

while True:
    pregunta = input("Tú: ")

    if pregunta.lower() == "salir":
        print("Chat finalizado.")
        break

    mensajes.append({
        "role": "user",
        "content": pregunta
    })

    respuesta = cliente.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=mensajes,
        temperature=0.3,
        max_tokens=500
    )

    texto = respuesta.choices[0].message.content

    mensajes.append({
        "role": "assistant",
        "content": texto
    })

    print("\nModelo:")
    print(texto)
    print(f"\nTokens usados: {respuesta.usage.total_tokens}")
    print("-" * 50)